### ISSUE TITLE
create mobile view low-fidelity wireframes

### ISSUE THREAD

**Issue by hyang-gi** [hyang-gi/kpopstop#13]

**Comment by zaynab-j** [comment]
Update: 

I'm done with the mobile view wireframes. Here is the link to the Figma project: 

https://www.figma.com/file/5G3J2FzO7nfsrqXDsmSi8S/Authoring-Project---Mobile-View-Wireframes?node-id=0%3A1&t=4tpe6rwzanWp4Ird-1

I will also be sending the pdf version in the WhatsApp group. Please talk a look and let me know if there is anything you want me to edit.

**Comment by hyang-gi** [comment]
@zaynab-j Thanks! This looks great. I had a couple of thoughts: 

1. Could you please change the colours to a grey version. As we haven't yet reached the colour theme selection stage, sticking with our website wireframes theme would be appropriate for consistency.

2. This wireframe version is slightly more advanced from the basic level, the website version will have to be updated with these changes (again) for the uniformity in designs.

**Comment by zaynab-j** [comment]
Thanks Nikhat for the suggestions!

The mobile view wireframes were updates as follows:

1- I changed the colours to grey tone ones as suggested. 
2- Didn't realize I added the Facebook icon instead of TikTok. Thanks for the note. Icon was changed to TikTok.
3- I couldn't change the font as I couldn't find 'Helvetica Nue'. The font used in the mobile version is 'Poppins' if change is necessary.

Here is the link to the updated version on Figma: 

https://www.figma.com/file/yoYmc1fdddzh4m981zYZ9C/KpopStop-Mobile-View-WireFrames?node-id=1302%3A14652
